# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_first_name', models.CharField(max_length=30)),
                ('client_email', models.EmailField(max_length=80)),
                ('client_phone', models.CharField(max_length=40)),
                ('client_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(unique=True)),
                ('order_data', models.DateField()),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LAB6_dj.ClientModel')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_price', models.CharField(max_length=20)),
                ('service_type', models.CharField(max_length=40)),
                ('service_class_of_price', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='order_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LAB6_dj.OrderModel'),
        ),
    ]
